CbeerDev/objects/Account_Auth_Feature__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CBBD Account Auths/Features</relationshipLabel>
        <relationshipName>Account_Auth_Features</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBI_US_Item_Authorization_Feature__c</fullName>
        <description>Store-level junction between Item Authorization/Feature record and Account</description>
        <label>CBBD US Item Authorization &amp; Feature</label>
        <referenceTo>CBI_US_Item_Authorization_Feature__c</referenceTo>
        <relationshipLabel>CBBD Account Auths/Features</relationshipLabel>
        <relationshipName>Account_Auth_Features</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>System_Managed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if junction object is managed by Store Set automation, or manually managed by user.</description>
        <label>System Managed</label>
        <type>Checkbox</type>
    </fields>
    <label>CBBD Account Auth/Feature</label>
    <nameField>
        <displayFormat>AAF-{0000}</displayFormat>
        <label>Account Auth/Feature Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBBD Account Auths/Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CbeerDev/objects/AsyncRequest__c.object
<CustomObject>
    <description>Stores asynchronous requests of Authorizations/Features with Store Sets to be processed, or Accounts with Store Set Criteria to be process, or any other new functionality down the road can be leveraged here.</description>
    <fields>
        <fullName>AsyncType__c</fullName>
        <description>Each picklist option drive a different business logic. As more business requirement leverage this Asynchronous framework, more picklist options can be added.</description>
        <label>AsyncType</label>
        <picklist>
            <picklistValues>
                <fullName>Store Set Automation For Item</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Error__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flags that an error occurred while processing this request. Can be unchecked to allow the Request to be processed again.</description>
        <label>Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Params__c</fullName>
        <description>This can be any data, in any format, that you want passed to the Asynchonous job. Most typically it will be a comma-delimited list of record IDs to be processed, such as Account IDs, or Auth/Feature IDs.</description>
        <label>Params</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CbeerDev/objects/AsyncRequestSetting__mdt.object
<CustomObject>
    <description>Configuration for AsyncRequestsQueueable class.</description>
    <fields>
        <fullName>AsyncType__c</fullName>
        <description>Must match AsyncRequest__c.AsyncType__c picklist values.</description>
        <label>AsyncType</label>
        <picklist>
            <picklistValues>
                <fullName>Store Set Automation For Item</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Default</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>AsyncRequest Setting</label>
    <pluralLabel>AsyncRequest Settings</pluralLabel>
</CustomObject>

CbeerDev/objects/CBI_US_Item_Authorization_Feature__c.object
<CustomObject>
    <description>Custom Item Authorization &amp; Feature object to create and store Item Authorizations and Features that will be used by other connected sources</description>
    <fields>
        <fullName>Add_all_Parent_Account_stores__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checkbox is checked, all child Accounts under Ultimate Parent Account will be automatically added as junction objects to the Item Auth/Feature</description>
        <label>Add all Parent Account stores</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BRAND_CD__c</fullName>
        <label>Brand Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FEATURE_PRICE__c</fullName>
        <label>Feature Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GTIN_NO__c</fullName>
        <label>Retailer UPC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MASTER_PKG_CD__c</fullName>
        <label>Master Package Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MASTER_SKU_CD__c</fullName>
        <label>Master SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Groups__c</fullName>
        <label>Marketing Groups</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NEW_SET_FLG__c</fullName>
        <label>New Set</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOTES_TXT__c</fullName>
        <label>Additional Notes</label>
        <length>290</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ON_MENU_FLG__c</fullName>
        <label>On Menu</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RESET_PERIOD_BEGIN_DT_ID__c</fullName>
        <label>Reset Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RESET_PERIOD_END_DT_ID__c</fullName>
        <label>Reset Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Report_To_Codes__c</fullName>
        <label>Report To Codes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SET_PERIOD_BEGIN_DT_ID__c</fullName>
        <label>Set Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SET_PERIOD_END_DT_ID__c</fullName>
        <label>Set Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Accounts__c</fullName>
        <label>Sub Accounts</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Type_CD__c</fullName>
        <label>Type Code</label>
        <picklist>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ultimate_Parent__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Ultimate Parent</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CBI_US_Collections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>CBBD US Item Authorization &amp; Feature</label>
    <nameField>
        <displayFormat>CFA -{0000}</displayFormat>
        <label>CBBD US Item Authorization &amp; Feature</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBBD US Item Authorizations &amp; Features</pluralLabel>
    <recordTypes>
        <fullName>Feature</fullName>
        <active>true</active>
        <description>Record Type for Feature</description>
        <label>Feature</label>
    </recordTypes>
    <recordTypes>
        <fullName>Item_Authorization</fullName>
        <active>true</active>
        <description>Record Type For Item Authorizations</description>
        <label>Item Authorization</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CbeerDev/classes/CBIUSStoreSetAutomationTest.cls
//Test class for testing following classes:
/*
// AsyncRequest__c
//AsyncRequestSetting__mdt

Triggers:
AccountTrigger.trigger (updated)
CBIUSItemAuthorizationFeatureTrigger.trigger (new)
AsyncRequestTrigger.trigger (new)

Classes:
AccountTriggerHandler (updated)
CBIUSItemFeatTriggerHandler (new) 
AsyncRequestTriggerHandler (new)
AsyncRequestQueueable (new) 
CBIUSStoreSetAutomation (new)
*/

@isTest
public class CBIUSStoreSetAutomationTest { 

	private static Id GetRTAuthOrFeature(String devName) {
		RecordType rt = [select id, Name from RecordType where SobjectType = 'CBI_US_Item_Authorization_Feature__c' and RecordType.DeveloperName = :devName Limit 1];
		System.assert(rt != null, 'Shouldve found recordtype for Auth/Feature');
		return rt.Id;
	}
	private static Id GetRTUSAccountId() {
		RecordType rt = [select id, Name FROM RecordType WHERE SobjectType = 'Account' AND RecordType.DeveloperName = 'US_Account' Limit 1];
		System.assert(rt != null, 'Shouldve found recordtype for Account.');
		return rt.Id;
	}
	private static Account MakeAccounts(Integer numStores, String billingState, String subAccount, String mGroup, String reportTo) {
		Account parentAcc = new Account(Name = 'ParentTestAcc', 
			Est_un_compte_parent__c = true);
		
		Id recordTypeUSAccount = GetRTUSAccountId();
		
		List<Account> accs = new List<Account>();
		for (Integer i = 0; i < numStores; i++) {
			Account a = new Account(Name = 'ChildTestAcc'+i, 
			SUBACCOUNT_DSC__c = subAccount,
			Marketing_Group__c = mGroup,
			RMA__c = reportTo,
			Est_un_compte_parent__c = false,
			BillingState = billingState, 
			BillingCity = 'SF', 
			BillingStreet = 'ST',
			RecordTypeId = recordTypeUSAccount);
			accs.add(a);
		}		
		TestUtil.createAccountAndSubAccounts(parentAcc, accs);
		
		return parentAcc;
	}

	@isTest
	private static void  TestEnqueue() {		
		Test.startTest();
		AsyncRequestQueueable.EnqueueAsyncJob(null);
		Test.stopTest();

		List<AsyncApexJob> jobs =
            [SELECT Id, Status, ExtendedStatus
            FROM AsyncApexJob
            WHERE JobType = 'Queueable' AND
            ApexClass.Name='AsyncRequestQueueable'];

		System.assertEquals(1, jobs.size(), 'Should find one job');
	}
	@isTest
	private static void  TestEnqueueFuture() {		
		Test.startTest();
		AsyncRequestQueueable.EnqueueAsyncJobFuture(null);
		Test.stopTest();

		List<AsyncApexJob> jobs =
            [SELECT Id, Status, ExtendedStatus
            FROM AsyncApexJob
            WHERE JobType = 'Queueable' AND
            ApexClass.Name='AsyncRequestQueueable'];

		System.assertEquals(1, jobs.size(), 'Should find one job');
	}

	@isTest
	private static void TestNoStoreSetCriteria() {
		TestUtil.createBulkProductsCBBD();
		Id itemRTID = GetRTAuthOrFeature('Feature');
		Account ultAcc = MakeAccounts(10,'CA','','','');

		Test.startTest();

		//Create the Feat with no Store set criteria, assert no Junctions were created.
		CBI_US_Item_Authorization_Feature__c item = defaultItem(ultAcc.Id, 'Feature', itemRTID);
		insert item;

		Test.stopTest();

		List<Account_Auth_Feature__c> stores = GetRelatedStores(item.Id);

		System.assertEquals(0, stores.size(), 'Should find no associated stores.');
	}
	@isTest
	private static void TestStateStoreSetCriteria() {
		TestUtil.createBulkProductsCBBD();		
		Account ultAcc  = MakeAccounts(10,'CA','','','');
		Id itemRTID = GetRTAuthOrFeature('Feature');

		Test.startTest();

		//Create the Feat with no Store set criteria, assert no Junctions were created.
		CBI_US_Item_Authorization_Feature__c item = defaultItem(ultAcc.Id, 'Feature', itemRTID);
		item.States__c = 'CA';
		insert item;
		
		Test.stopTest();

		System.assertEquals(10, GetRelatedStores(item.Id).size(), 'Should find 10 associated stores with CA BillingState.');	
	}
	@isTest
	private static void TestStateStoreSetCriteriaUpdate() {
		TestUtil.createBulkProductsCBBD();		
		Account ultAcc  = MakeAccounts(10,'CA','','','');
		Id itemRTID = GetRTAuthOrFeature('Feature');

		//Create the Feat with no Store set criteria, assert no Junctions were created.
		CBI_US_Item_Authorization_Feature__c item = defaultItem(ultAcc.Id, 'Feature', itemRTID);
		item.States__c = 'CA';
		insert item;

		Test.startTest();

		item.States__c = '';
		update item;
		
		Test.stopTest();

		System.assertEquals(0, GetRelatedStores(item.Id).size(), 'Should find 0 associated stores with CA BillingState.');	
	}
	@isTest
	private static void TestSubAccountStoreSetCriteria() {
		TestUtil.createBulkProductsCBBD();		
		Account ultAcc  = MakeAccounts(10,'CA','SubAccountA','','');
		Id itemRTID = GetRTAuthOrFeature('Feature');

		Test.startTest();

		//Create the Feat with no Store set criteria, assert no Junctions were created.
		CBI_US_Item_Authorization_Feature__c item = defaultItem(ultAcc.Id, 'Feature', itemRTID);
		item.Sub_Accounts__c = 'SubAccountA';
		insert item;
		
		Test.stopTest();

		System.assertEquals(10, GetRelatedStores(item.Id).size(), 'Should find 10 associated stores with SubAccountA .');	
	}
	@isTest
	private static void TestSubAccountStoreSetCriteriaUpdate() {
		TestUtil.createBulkProductsCBBD();		
		Account ultAcc  = MakeAccounts(10,'CA','SubAccountA','','');
		Id itemRTID = GetRTAuthOrFeature('Feature');

		//Create the Feat with no Store set criteria, assert no Junctions were created.
		CBI_US_Item_Authorization_Feature__c item = defaultItem(ultAcc.Id, 'Feature', itemRTID);
		item.Sub_Accounts__c = 'SubAccountA';
		insert item;

		Test.startTest();

		item.Sub_Accounts__c = '';
		update item;
		
		Test.stopTest();

		System.assertEquals(0, GetRelatedStores(item.Id).size(), 'Should find 0 associated stores with SubAccountA .');	
	}
	@isTest
	private static void TestMarketingGroupStoreSetCriteria() {
		TestUtil.createBulkProductsCBBD();		
		Account ultAcc  = MakeAccounts(10,'CA','','MGroup1','');
		Id itemRTID = GetRTAuthOrFeature('Feature');

		Test.startTest();

		//Create the Feat with no Store set criteria, assert no Junctions were created.
		CBI_US_Item_Authorization_Feature__c item = defaultItem(ultAcc.Id, 'Feature', itemRTID);
		item.Marketing_Groups__c = 'MGroup1';
		insert item;
		
		Test.stopTest();

		System.assertEquals(10, GetRelatedStores(item.Id).size(), 'Should find 10 associated stores with MGroup1 .');	
	}
	@isTest
	private static void TestMarketingGroupStoreSetCriteriaUpdate() {
		TestUtil.createBulkProductsCBBD();		
		Account ultAcc  = MakeAccounts(10,'CA','','MGroup1','');
		Id itemRTID = GetRTAuthOrFeature('Feature');

		//Create the Feat with no Store set criteria, assert no Junctions were created.
		CBI_US_Item_Authorization_Feature__c item = defaultItem(ultAcc.Id, 'Feature', itemRTID);
		item.Marketing_Groups__c = 'MGroup1';
		insert item;

		Test.startTest();

		item.Marketing_Groups__c = '';
		update item;
		
		Test.stopTest();

		System.assertEquals(0, GetRelatedStores(item.Id).size(), 'Should find 0 associated stores with MGroup1 .');	
	}
	@isTest
	private static void TestReportToStoreSetCriteria() {
		TestUtil.createBulkProductsCBBD();		
		Account ultAcc  = MakeAccounts(10,'CA','','','ReportTo1');
		Id itemRTID = GetRTAuthOrFeature('Feature');

		Test.startTest();

		//Create the Feat with no Store set criteria, assert no Junctions were created.
		CBI_US_Item_Authorization_Feature__c item = defaultItem(ultAcc.Id, 'Feature', itemRTID);
		item.Report_To_Codes__c = 'ReportTo1';
		insert item;
		
		Test.stopTest();

		System.assertEquals(10, GetRelatedStores(item.Id).size(), 'Should find 10 associated stores with ReportTo1 .');	
	}
	@isTest
	private static void TestReportToStoreSetCriteriaUpdate() {
		TestUtil.createBulkProductsCBBD();		
		Account ultAcc  = MakeAccounts(10,'CA','','','ReportTo1');
		Id itemRTID = GetRTAuthOrFeature('Feature');

		//Create the Feat with no Store set criteria, assert no Junctions were created.
		CBI_US_Item_Authorization_Feature__c item = defaultItem(ultAcc.Id, 'Feature', itemRTID);
		item.Report_To_Codes__c = 'ReportTo1';
		insert item;

		Test.startTest();

		item.Report_To_Codes__c = '';
		update item;
		
		Test.stopTest();

		System.assertEquals(0, GetRelatedStores(item.Id).size(), 'Should find 0 associated stores with ReportTo1 .');	
	}
	@isTest
	private static void TestCheckAllStoresSetCriteria() {
		TestUtil.createBulkProductsCBBD();		
		Account ultAcc  = MakeAccounts(200,'CA','','','');
		Id itemRTID = GetRTAuthOrFeature('Feature');

		Test.startTest();

		//Create the Feat with no Store set criteria, assert no Junctions were created.
		CBI_US_Item_Authorization_Feature__c item = defaultItem(ultAcc.Id, 'Feature', itemRTID);
		item.Add_all_Parent_Account_stores__c = true;
		insert item;
		
		Test.stopTest();

		System.assertEquals(200, GetRelatedStores(item.Id).size(), 'Should find 200 associated stores.');	
	}
	@isTest
	private static void TestCheckAllStoresSetCriteriaUpdate() {
		TestUtil.createBulkProductsCBBD();		
		Account ultAcc  = MakeAccounts(200,'CA','','','');
		Id itemRTID = GetRTAuthOrFeature('Feature');
		
		//Create the Feat with no Store set criteria, assert no Junctions were created.
		CBI_US_Item_Authorization_Feature__c item = defaultItem(ultAcc.Id, 'Feature', itemRTID);
		item.Add_all_Parent_Account_stores__c = true;
		insert item;

		Test.startTest();

		item.Add_all_Parent_Account_stores__c = false;
		update item;		
		
		Test.stopTest();

		System.assertEquals(0, GetRelatedStores(item.Id).size(), 'Should find 0 associated stores.');	
	}
	@isTest
	private static void TestCheckAllStoresSetCriteriaUpdateTry2() {
		TestUtil.createBulkProductsCBBD();		
		Account ultAcc  = MakeAccounts(200,'CA','','','');
		Id itemRTID = GetRTAuthOrFeature('Feature');
		
		
		Test.startTest();

		//Create the Feat with no Store set criteria, assert no Junctions were created.
		CBI_US_Item_Authorization_Feature__c item = defaultItem(ultAcc.Id, 'Feature', itemRTID);
		item.Add_all_Parent_Account_stores__c = true;
		insert item;

		item.Add_all_Parent_Account_stores__c = false;
		update item;		
		
		Test.stopTest();

		System.assertEquals(0, GetRelatedStores(item.Id).size(), 'Should find 0 associated stores.');	
	}
	@isTest
	private static void TestCreateAccount() {
		TestUtil.createBulkProductsCBBD();		
		Account ultAcc  = MakeAccounts(0,'CA','','','');
		Id itemRTID = GetRTAuthOrFeature('Feature');
		Id recordTypeUSAccount = GetRTUSAccountId();
		
		//Create the Feat with all storesc checked, (but no stores exists)
		CBI_US_Item_Authorization_Feature__c item = defaultItem(ultAcc.Id, 'Feature', itemRTID);
		item.Add_all_Parent_Account_stores__c = true;
		insert item;

		Test.startTest();

		Account sub1  = new Account(Name = 'ChildTestAcc', 
			ParentId = ultAcc.Id,
			SUBACCOUNT_DSC__c = '',
			Marketing_Group__c = '',
			RMA__c = '',
			Est_un_compte_parent__c = false,
			BillingState = 'AZ', 
			BillingCity = 'SF', 
			BillingStreet = 'ST',
			RecordTypeId = recordTypeUSAccount);

		insert sub1;	
		
		Test.stopTest();

		List<Account_Auth_Feature__c> junctions = GetRelatedStores(item.Id);

		System.assertEquals(1, junctions.size(), 'Should find 1 associated stores.');	
		System.assertEquals(sub1.Id, junctions[0].Account__c, 'Should match the one store created.');
	}
	@isTest
	private static void TestUpdateAccount() {
		TestUtil.createBulkProductsCBBD();		
		Account ultAcc  = MakeAccounts(1,'CA','','','');
		Id itemRTID = GetRTAuthOrFeature('Feature');
		Id recordTypeUSAccount = GetRTUSAccountId();

		Account sub1 = [SELECT Id, BillingState FROM Account WHERE ParentId = :ultAcc.Id LIMIT 1];
		System.assert(sub1 != null, 'Should have found 1 created child account.');
		
		CBI_US_Item_Authorization_Feature__c item = defaultItem(ultAcc.Id, 'Feature', itemRTID);
		item.States__c = 'AZ';
		insert item;

		Test.startTest();

		sub1.BillingState = 'AZ';
		update sub1;	
		
		Test.stopTest();

		List<Account_Auth_Feature__c> junctions = GetRelatedStores(item.Id);

		System.assertEquals(1, junctions.size(), 'Should find 1 associated stores.');	
		System.assertEquals(sub1.Id, junctions[0].Account__c, 'Should match the one store created.');
	}

	@isTest
	private static void TestAsyncRequestTriggerHandler(){

	AsyncRequestTriggerHandler a = new AsyncRequestTriggerHandler();

	}

	@isTest
	private static void TestBadParams() {
		AsyncRequest__c req = new AsyncRequest__c(AsyncType__c = AsyncRequestQueueable.TYPE_STORE_SET_AUTOMATION_ITEM,
			Params__c = '');

		Test.startTest();

		insert req;
		
		Test.stopTest();

		List<AsyncRequest__c> requests = [SELECT Id, Error__c FROM AsyncRequest__c];

		System.assertEquals(1, requests.size(), 'Should find 1 request record');	
		System.assertEquals(true, requests[0].Error__c, 'Should be marked as error.');
	}
	
	private static List<Account_Auth_Feature__c> GetRelatedStores(Id itemId) {
		return [SELECT Id, System_Managed__c, Account__c, Account__r.Name, CBI_US_Item_Authorization_Feature__c 
                    FROM Account_Auth_Feature__c where CBI_US_Item_Authorization_Feature__c = :itemId];
	}

	public static CBI_US_Item_Authorization_Feature__c defaultItem(ID parentID, String rtDevName, Id rtId) {
		
		CBI_US_Item_Authorization_Feature__c rec = new CBI_US_Item_Authorization_Feature__c();
		rec.RecordTypeID = rtId;		
		if (rtDevName == 'Feature') {
			rec.Type_CD__c = 'BE';
		} else if(rtDevName == 'Item_Authorization'){
			rec.Type_CD__c = 'CM';
		}
		rec.Ultimate_Parent__c = parentID;
		rec.Sub_Accounts__c = '';
		rec.NEW_SET_FLG__c = '';
		rec.ON_MENU_FLG__c = '';
		rec.NOTES_TXT__c = '';
		rec.Brand_Cd__c = 'b123450';
		rec.MASTER_PKG_CD__c = 'p123450';
		rec.MASTER_SKU_CD__c = '';
		rec.GTIN_NO__c = null;
		rec.FEATURE_PRICE__c = 12.99;
		rec.SET_PERIOD_BEGIN_DT_ID__c = Date.Today();
		rec.SET_PERIOD_END_DT_ID__c = Date.Today();
		rec.RESET_PERIOD_BEGIN_DT_ID__c = Date.Today();
		rec.RESET_PERIOD_END_DT_ID__c = Date.Today();
		rec.Add_all_Parent_Account_stores__c = false;
		rec.Sub_Accounts__c = '';
		rec.Marketing_Groups__c = '';
		rec.Report_To_Codes__c = '';
		rec.States__c = '';
		return rec;
	}

	

}