CbeerDev/objects/Account_Auth_Feature__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CBBD Account Auths/Features</relationshipLabel>
        <relationshipName>Account_Auth_Features</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBI_US_Item_Authorization_Feature__c</fullName>
        <description>Store-level junction between Item Authorization/Feature record and Account</description>
        <label>CBBD US Item Authorization &amp; Feature</label>
        <referenceTo>CBI_US_Item_Authorization_Feature__c</referenceTo>
        <relationshipLabel>CBBD Account Auths/Features</relationshipLabel>
        <relationshipName>Account_Auth_Features</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CBBD Account Auth/Feature</label>
    <nameField>
        <displayFormat>AAF-{0000}</displayFormat>
        <label>Account Auth/Feature Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBBD Account Auths/Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CbeerDev/objects/CBI_US_Item_Authorization_Feature__c.object
<CustomObject>
    <description>Custom Item Authorization &amp; Feature object to create and store Item Authorizations and Features that will be used by other connected sources</description>
    <fields>
        <fullName>Add_all_Parent_Account_stores__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checkbox is checked, all child Accounts under Ultimate Parent Account will be automatically added as junction objects to the Item Auth/Feature</description>
        <label>Add all Parent Account stores</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BRAND_CD__c</fullName>
        <label>Brand Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FEATURE_PRICE__c</fullName>
        <label>Feature Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MASTER_PKG_CD__c</fullName>
        <label>Master Package Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MASTER_SKU_CD__c</fullName>
        <label>Master SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Groups__c</fullName>
        <label>Marketing Groups</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NEW_SET_FLG__c</fullName>
        <label>New Set</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOTES_TXT__c</fullName>
        <label>Additional Notes</label>
        <length>290</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ON_MENU_FLG__c</fullName>
        <label>On Menu</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RESET_PERIOD_BEGIN_DT_ID__c</fullName>
        <label>Reset Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RESET_PERIOD_END_DT_ID__c</fullName>
        <label>Reset Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Report_To_Codes__c</fullName>
        <label>Report To Codes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SET_PERIOD_BEGIN_DT_ID__c</fullName>
        <label>Set Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SET_PERIOD_END_DT_ID__c</fullName>
        <label>Set Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Accounts__c</fullName>
        <label>Sub Accounts</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TYPE_DSC__c</fullName>
        <formula>IF(AND(ISPICKVAL(Type_CD__c, &quot;BE&quot;), RecordType.DeveloperName = &quot;Feature&quot;), &quot;Beer of the Month&quot;,
   IF(AND(ISPICKVAL(Type_CD__c, &quot;HH&quot;),RecordType.DeveloperName = &quot;Feature&quot;), &quot;Happy Hour&quot;,
      IF(AND(ISPICKVAL(Type_CD__c, &quot;LP&quot;),RecordType.DeveloperName = &quot;Feature&quot;), &quot;Every Day Low Price&quot;,
         IF(AND(ISPICKVAL(Type_CD__c, &quot;LT&quot;),RecordType.DeveloperName = &quot;Feature&quot;), &quot;Limited Time Only (LTO)&quot;,
            IF(AND(ISPICKVAL(Type_CD__c, &quot;be&quot;),RecordType.DeveloperName = &quot;Feature&quot;), &quot;Beer of the Month&quot;,
               IF(AND(ISPICKVAL(Type_CD__c, &quot;hh&quot;),RecordType.DeveloperName = &quot;Feature&quot;), &quot;Happy Hour&quot;,
                  IF(AND(ISPICKVAL(Type_CD__c, &quot;lp&quot;),RecordType.DeveloperName = &quot;Feature&quot;), &quot;Every Day Low Price&quot;,
                     IF(AND(ISPICKVAL(Type_CD__c, &quot;lt&quot;),RecordType.DeveloperName = &quot;Feature&quot;), &quot;Limited Time Only (LTO)&quot;,
IF(AND(ISPICKVAL(Type_CD__c, &quot;OS&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Authorized - Optional (Sell-In)&quot;,
   IF(AND(ISPICKVAL(Type_CD__c, &quot;SP&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Authorized - Select Planogram&quot;,
      IF(AND(ISPICKVAL(Type_CD__c, &quot;BM&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Brand Mandated - Any Format&quot;,
         IF(AND(ISPICKVAL(Type_CD__c, &quot;CM&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Corporate Mandate&quot;,
            IF(AND(ISPICKVAL(Type_CD__c, &quot;NA&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Not Applicable&quot;,
               IF(AND(ISPICKVAL(Type_CD__c,&quot;PA&quot;), RecordType.DeveloperName = &quot;Item_Authorization&quot;),&quot;Pending Authorization&quot;,
                  IF(AND(ISPICKVAL(Type_CD__c, &quot;PN&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Presented - Not Authorized&quot;,
                     IF(AND(ISPICKVAL(Type_CD__c, &quot;TB&quot;), RecordType.DeveloperName = &quot;Item_Authorization&quot;),&quot;To be Presented&quot;,
                        IF(AND(ISPICKVAL(Type_CD__c, &quot;os&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Authorized - Optional (Sell-In)&quot;,
                           IF(AND(ISPICKVAL(Type_CD__c, &quot;sp&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Authorized - Select Planogram&quot;,
                             IF(AND(ISPICKVAL(Type_CD__c, &quot;bm&quot;), RecordType.DeveloperName = &quot;Item_Authorization&quot;),&quot;Brand Mandated - Any Format&quot;,
                                 IF(AND(ISPICKVAL(Type_CD__c, &quot;cm&quot;), RecordType.DeveloperName = &quot;Item_Authorization&quot;),&quot;Corporate Mandate&quot;,
                                    IF(AND(ISPICKVAL(Type_CD__c, &quot;na&quot;), RecordType.DeveloperName = &quot;Item_Authorization&quot;),&quot;Not Applicable&quot;,
                                      IF(AND(ISPICKVAL(Type_CD__c, &quot;pa&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Pending Authorization&quot;,
                                               IF(AND(ISPICKVAL(Type_CD__c, &quot;pn&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Presented - Not Authorized&quot;,
                                                       IF(AND(ISPICKVAL(Type_CD__c, &quot;tb&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;To be Presented&quot;, null))))))))))))))))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ultimate_Parent__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Ultimate Parent</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CBI_US_Collections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>CBBD US Item Authorization &amp; Feature</label>
    <nameField>
        <displayFormat>CFA -{0000}</displayFormat>
        <label>CBBD US Item Authorization &amp; Feature</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBBD US Item Authorizations &amp; Features</pluralLabel>
    <recordTypes>
        <fullName>Feature</fullName>
        <active>true</active>
        <description>Record Type for Feature</description>
        <label>Feature</label>
    </recordTypes>
    <recordTypes>
        <fullName>Item_Authorization</fullName>
        <active>true</active>
        <description>Record Type For Item Authorizations</description>
        <label>Item Authorization</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CbeerDev/classes/CBIUSCollectionsEditCtrl.cls
public with sharing class CBIUSCollectionsEditCtrl extends CBIUSCollectionsCtrlBase
{
	public String currentAuthFeatureId { get; set; }

	public ItemWrapper Wrapper { get; set; }

	public CBIUSCollectionsUtility.AccountHierarchy Hierarchy { get; set; }
	public List<CBIUSCollectionsUtility.JSOption> Brands { get; set; }
	public List<CBIUSCollectionsUtility.JSOption> SkusPackages { get; set; }

	public String BrandDisplay { get; set; }
	public String PkgSkuDisplay { get; set; }

	public String TDLinxCodesToAdd { get; set; }
	public String StoresToRemove { get; set; }

	//public CBI_US_Item_Authorization_Feature__c similar { get; set; }




	public CBIUSCollectionsEditCtrl() {
		//Set variables
		currentAuthFeatureId = ApexPages.currentPage().getParameters().get('cid');

		system.debug(currentAuthFeatureId);
		TDLinxCodesToAdd = '';
		StoresToRemove = '';
		//Validate querystring
		if (String.isBlank(currentAuthFeatureId)) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'URL missing Auth/Feature Id, cannot continue.'));
			return;
		}
		//SOQL for Auth/Feature
		RefreshItem();
		//Build Sales Hierarchy options for SubAccounts, MarketingGroups, ReportTos.
		Hierarchy = CBIUSCollectionsUtility.RetrieveAccountHierarchy(Wrapper.Item.Ultimate_Parent__c);
		Brands = CBIUSCollectionsUtility.RetrieveBrands();

		//Based on BRAND_CD__c, find the display name.
		for (CBIUSCollectionsUtility.JSOption b : Brands) {
			if (b.OptionId == Wrapper.Item.BRAND_CD__c) {
				BrandDisplay = b.OptionLabel;
				break;
			}
		}
		//Determine if the Auth/Feat is SKU or Package oriented
		String pkgOrSku = '';
		String pkgOrSkuCode = '';
		if (!String.isEmpty(Wrapper.Item.MASTER_PKG_CD__c)) {
			pkgOrSku = CBIUSCollectionsUtility.PKG;
			pkgOrSkuCode = Wrapper.Item.MASTER_PKG_CD__c;
		}
		if (!String.isEmpty(Wrapper.Item.MASTER_SKU_CD__c)) {
			pkgOrSku = CBIUSCollectionsUtility.SKU;
			pkgOrSkuCode = Wrapper.Item.MASTER_SKU_CD__c;
		}
		//Retrieve the possible Pkgs/Skus and iterate them to find the correct Display. Keep in mind
		//there could be multiple codes for a given description, separated by |
		SkusPackages = CBIUSCollectionsUtility.RetrieveSkusOrPackages(Wrapper.Item.BRAND_CD__c, pkgOrSku);
		for (CBIUSCollectionsUtility.JSOption o : SkusPackages) {
			if (o.OptionId.contains(pkgOrSkuCode)) {
				PkgSkuDisplay = o.OptionLabel;
				break;
			}
		}

	}
	private void RefreshItem() {
		//Query for Feature/Auth and build wrapper to support UI
		CBI_US_Item_Authorization_Feature__c theItem = [SELECT Id, Add_all_Parent_Account_stores__c, Ultimate_Parent__c, Ultimate_Parent__r.Name, Name, RecordType.Name, RecordType.DeveloperName, TYPE_DSC__c, BRAND_CD__c, MASTER_PKG_CD__c, MASTER_SKU_CD__c, SET_PERIOD_BEGIN_DT_ID__c, SET_PERIOD_END_DT_ID__c, RESET_PERIOD_BEGIN_DT_ID__c, RESET_PERIOD_END_DT_ID__c, Sub_Accounts__c, States__c, Report_To_Codes__c, Marketing_Groups__c, NOTES_TXT__c, ON_MENU_FLG__c, NEW_SET_FLG__c, FEATURE_PRICE__c FROM CBI_US_Item_Authorization_Feature__c WHERE Id = :currentAuthFeatureId LIMIT 1];
		Wrapper = new ItemWrapper(theItem);
	}
	public PageReference CreateSimilar() {
	 System.debug('this is the developer name: ' + Wrapper.item.RecordType.DeveloperName);
		PageReference p;
		if (Wrapper.item.RecordType.DeveloperName == 'Item_Authorization') {
			p = Page.cbiusitemauthorizationcreate;
			
		} else {
			p = Page.cbiusfeaturecreate;
		}
		    p.getParameters().put('cid', Wrapper.item.id);
			p.setRedirect(true);
			return p;
	}
	public void SaveItem() {
		try {
			Wrapper.Item.SET_PERIOD_END_DT_ID__c = CBIUSCollectionsUtility.makeDate(Wrapper.EndDate);
			Wrapper.Item.RESET_PERIOD_BEGIN_DT_ID__c = CBIUSCollectionsUtility.makeDate(Wrapper.ResetStartDate);
			Wrapper.Item.RESET_PERIOD_END_DT_ID__c = CBIUSCollectionsUtility.makeDate(Wrapper.ResetEndDate);
			Wrapper.Item.NEW_SET_FLG__c = Wrapper.NewSet;
			Wrapper.Item.ON_MENU_FLG__c = Wrapper.OnMenu;
			Wrapper.Item.Sub_Accounts__c = Wrapper.SubAccountsDisplay;
			Wrapper.Item.Marketing_Groups__c = Wrapper.MarketingGroupsDisplay;
			Wrapper.Item.Report_To_Codes__c = Wrapper.ReportTosDisplay;
			Wrapper.Item.States__c = Wrapper.StatesDisplay;
			Wrapper.Item.FEATURE_PRICE__c = (Wrapper.Item.RecordType.DeveloperName == 'Feature' && !String.isBlank(Wrapper.Price)) ? Decimal.valueOf(Wrapper.Price) : null;
			Wrapper.Item.Add_all_Parent_Account_stores__c = Wrapper.AddAllParentsDisplay;
			update Wrapper.Item;
		} catch(System.DmlException dmle) {
			ApexPages.addMessages(dmle);
		} catch(Exception e) {
			ApexPages.addMessages(e);
		}
	}
	public void EndItemToday() {
		try {
			Wrapper.Item.SET_PERIOD_END_DT_ID__c = Date.today();
			update Wrapper.Item;
		} catch(System.DmlException dmle) {
			ApexPages.addMessages(dmle);
		} catch(Exception e) {
			ApexPages.addMessages(e);
		}
	}
	public void SaveStoresByTDLinxCodes() {
		Set<String> requestedTDLinx = new Set<String> ();
		Set<String> foundTDLinxCodes = new Set<String> ();
		List<Account_Auth_Feature__c> stores = new List<Account_Auth_Feature__c> ();
		Boolean isError = false;

		//Validate
		if (String.isBlank(TDLinxCodesToAdd)) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please supply at least 1 TDLinx Submission Code.'));
			TDLinxCodesToAdd = '';
			return;
		}
		List<String> tdLinxCodes = TDLinxCodesToAdd.split(',');
		if (tdLinxCodes.size() < 1) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please supply at least 1 TDLinx Submission Code.'));
			TDLinxCodesToAdd = '';
			return;
		}
		//Remember which TDLinx were requested in a set.
		requestedTDLinx.addAll(tdLinxCodes);

		//Find Accounts that match TDLinx Code (Store_Code__c)		
		for (Account a :[SELECT Id, Store_Code__c FROM Account WHERE Parent.Id = :Wrapper.Item.Ultimate_Parent__c AND Store_Code__c IN :tdLinxCodes]) {
			//Create junction record
			stores.add(new Account_Auth_Feature__c(Account__c = a.Id, CBI_US_Item_Authorization_Feature__c = currentAuthFeatureId));
			//Remember the TDLinx was found.
			foundTDLinxCodes.add(a.Store_Code__c);
		}
		//Validate stores found
		if (foundTDLinxCodes.size() < 1) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No Stores matched your TDLinx Submission Code(s).'));
			TDLinxCodesToAdd = '';
			return;
		}
		if (foundTDLinxCodes.size() != requestedTDLinx.size()) {
		System.debug('this is the found code: ' + foundTDLinxCodes);
		System.debug('this is the requested code: ' + requestedTDLinx);
			isError = true;
			String msg = 'The following TDLinx Codes were not found: ';
			List<String> tmpNotFound = new List<String> ();
			for (String s : requestedTDLinx) {
				if (!foundTDLinxCodes.contains(s)) {
					tmpNotFound.add(s);
				}
			}
			msg += String.join(tmpNotFound, ', ');
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning, msg));
		}

		//Use Database class Insert to allow partial save
		Integer foundCount = stores.size();
		Integer successResults = 0;
		Integer failures = 0;
		Database.SaveResult[] results = Database.insert(stores, false);
		for (Database.SaveResult sr : results) {
			if (sr.isSuccess()) {
				successResults++;
			} else {
				failures++;
				IsError = true;
				for (Database.Error err : sr.getErrors()) {
					ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, err.getMessage()));
				}
			}
		}
		if (successResults != foundCount || IsError == true) {
			String msg2 = 'Store(s) attempted: ' + foundCount + ', Store(s) add succesfully: ' + successResults + ', Store(s) failed: ' + failures;
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, msg2));
		}
		//Clear out TDLinx Codes		
		TDLinxCodesToAdd = '';
		return;
	}
	public void RemoveStores() {
		Boolean IsError = false;
		Integer successResults = 0;
		Integer failures = 0;
		if (String.isBlank(StoresToRemove)) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please choose at least one store to remove.'));
			StoresToRemove = '';
			return;
		}
		List<String> removeIds = StoresToRemove.split(',');
		List<Account_Auth_Feature__c> recs = new List<Account_Auth_Feature__c> ();
		try {
			for (String s : removeIds) {
				recs.add(new Account_Auth_Feature__c(Id = Id.valueOf(s.trim())));
			}
			Database.DeleteResult[] results = Database.delete(recs, false);
			for (Database.DeleteResult sr : results) {
				if (sr.isSuccess()) {
					successResults++;
				} else {
					failures++;
					IsError = true;
					for (Database.Error err : sr.getErrors()) {
						ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, err.getMessage()));
					}
				}
			}
			if (successResults != removeIds.size() || IsError == true) {
				String msg2 = 'Store(s) to be removed: ' + removeIds.size() + ', Store(s) removed succesfully: ' + successResults + ', Store(s) failed: ' + failures;
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, msg2));
			}
		} catch(System.DmlException dmle) {
			ApexPages.addMessages(dmle);
		} catch(Exception e) {
			ApexPages.addMessages(e);
		}
		StoresToRemove = '';
	}

	public class SuccessErrorResponse {
		public List<String> SuccessMsgs { get; set; }
		public List<String> ErrorMsgs { get; set; }
		public SuccessErrorResponse() {
			SuccessMsgs = new List<String> ();
			ErrorMsgs = new List<String> ();
		}
	}

	public class ItemWrapper {
		public CBI_US_Item_Authorization_Feature__c Item { get; set; }
		public String StartDate { get; set; }
		public String EndDate { get; set; }
		public String ResetStartDate { get; set; }
		public String ResetEndDate { get; set; }
		public String NewSet { get; set; }
		public String OnMenu { get; set; }
		public String Price { get; set; }
		public String SubAccountsDisplay { get; set; }
		public String MarketingGroupsDisplay { get; set; }
		public String ReportTosDisplay { get; set; }
		public String StatesDisplay { get; set; }
		public Boolean AddAllParentsDisplay { get; set; }

		public ItemWrapper(CBI_US_Item_Authorization_Feature__c i) {
			this.Item = i;
			this.StartDate = GetDateStringOrSpace(i.SET_PERIOD_BEGIN_DT_ID__c);
			this.EndDate = GetDateStringOrSpace(i.SET_PERIOD_END_DT_ID__c);
			this.ResetStartDate = GetDateStringOrSpace(i.RESET_PERIOD_BEGIN_DT_ID__c);
			this.ResetEndDate = GetDateStringOrSpace(i.RESET_PERIOD_END_DT_ID__c);
			this.NewSet = GetBoolValueOrNo(i.NEW_SET_FLG__c);
			this.OnMenu = GetBoolValueOrNo(i.ON_MENU_FLG__c);
			this.SubAccountsDisplay = TurnPipeDelimitedToStringOrSpace(i.Sub_Accounts__c);
			this.MarketingGroupsDisplay = TurnPipeDelimitedToStringOrSpace(i.Marketing_Groups__c);
			this.ReportTosDisplay = TurnPipeDelimitedToStringOrSpace(i.Report_To_Codes__c);
			this.StatesDisplay = TurnPipeDelimitedToStringOrSpace(i.States__c);
			this.Price = i.FEATURE_PRICE__c != null ? i.FEATURE_PRICE__c.format() : '';
			this.AddAllParentsDisplay = i.Add_all_Parent_Account_stores__c;
		}



		public String GetDateStringOrSpace(Date d) {
			if (d != null) {
				return d.format();
			}
			return 'None';
		}
		public String GetBoolValueOrNo(String s) {
			if (!String.isBlank(s)) {
				return s;
			}
			return 'No';
		}
		public String TurnPipeDelimitedToStringOrSpace(String s) {
			if (!String.isBlank(s)) {
				List<String> values = s.split('\\|');
				return String.join(values, ', ');
			}
			return 'None';
		}
		
	}
}