CbeerDev/objects/Account_Auth_Feature__c.object
<CustomObject>
    <fields>
        <fullName>Store_CD__c</fullName>
        <formula>Account__r.Store_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store Code</label>
        <type>Text</type>
    </fields>
    <label>CBBD Account Auth/Feature</label>
    <nameField>
        <displayFormat>AAF-{0000}</displayFormat>
        <label>Account Auth/Feature Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBBD Account Auths/Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CbeerDev/classes/CBIUSCollectionDelAccountAuthFeat.cls
global class CBIUSCollectionDelAccountAuthFeat implements Schedulable {
	/**
	 * @description Executes the scheduled Apex job. 
	 * @param sc contains the job ID
	 */ 

	global void execute(SchedulableContext sc) {
		String query = 'SELECT Id FROM Account_Auth_Feature__c where Store_CD__c = null';
        CBIUSCollectionsDelRecsBatchable b = new CBIUSCollectionsDelRecsBatchable(query);
        database.executebatch(b);
	}
}