CbeerDev/objects/Account_Auth_Feature__c.object
<CustomObject>
    <fields>
        <fullName>CBI_US_Item_Authorization_Feature__c</fullName>
        <description>Store-level junction between Item Authorization/Feature record and Account</description>
        <label>CBBD US Item Authorization &amp; Feature</label>
        <referenceTo>CBI_US_Item_Authorization_Feature__c</referenceTo>
        <relationshipLabel>CBBD Account Auths/Features</relationshipLabel>
        <relationshipName>Account_Auth_Features</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Store_CD__c</fullName>
        <formula>Account__r.Store_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Store Code</label>
        <type>Text</type>
    </fields>
    <label>CBBD Account Auth/Feature</label>
    <nameField>
        <displayFormat>AAF-{0000}</displayFormat>
        <label>Account Auth/Feature Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBBD Account Auths/Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

CbeerDev/objects/CBI_US_Item_Authorization_Feature__c.object
<CustomObject>
    <description>Custom Item Authorization &amp; Feature object to create and store Item Authorizations and Features that will be used by other connected sources</description>
    <fields>
        <fullName>Deletion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if a record has been inactive for 1 year and is scheduled for deletion</description>
        <label>Deletion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SET_PERIOD_END_DT_ID__c</fullName>
        <label>Set Period End</label>
        <type>Date</type>
    </fields>
    <label>CBBD US Item Authorization &amp; Feature</label>
    <nameField>
        <displayFormat>CFA -{0000}</displayFormat>
        <label>CBBD US Item Authorization &amp; Feature</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBBD US Item Authorizations &amp; Features</pluralLabel>
    <recordTypes>
        <fullName>Feature</fullName>
        <active>true</active>
        <description>Record Type for Feature</description>
        <label>Feature</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CbeerDev/classes/CBIUSCollectionsDelRecsBatchableTest.cls
@isTest
private class CBIUSCollectionsDelRecsBatchableTest {

	@isTest static void testCBIUSItemAuthDeleted() {

		//The query used by the batch job
		String query = 'SELECT Id FROM CBI_US_Item_Authorization_Feature__c where Deletion__c = true AND SET_PERIOD_END_DT_ID__c != null ';

		//Create Test Data
		
		TestUtil.createBulkValidItemAuthFlag2Del();

		//Start Test
		Test.startTest();
		CBIUSCollectionsDelRecsBatchable b = new CBIUSCollectionsDelRecsBatchable(query);
		database.executebatch(b);
		Test.stopTest();

		//verify cbi us item authorizations were deleted
		Integer i = [SELECT count() FROM CBI_US_Item_Authorization_Feature__c where Deletion__c = true AND SET_PERIOD_END_DT_ID__c != null ];
		System.assertEquals(i, 0);

	}

	@isTest static void testCBIUSItemAccountAuthDeleted() {

		//The query used by the batch job
		String query = 'SELECT Id FROM Account_Auth_Feature__c where Store_CD__c = null ';

		//Create Test Data
		//TestUtil.createBulkProducts();
		Account parent = new Account(Name='Parent Account',Est_un_compte_parent__c = true);		
		insert parent;
		Account child = new Account(name = 'Child Account',parentid = parent.id,Store_Code__c = '123');
		insert child;	

		CBI_US_Item_Authorization_Feature__c ia = TestUtil.createItemAuthOrFeature(parent.id, 'Feature');
		Account_Auth_Feature__c aa= TestUtil.createAccountAuthFeat(child.id, ia.id);

		delete child;

		//Start Test
		Test.startTest();
		CBIUSCollectionsDelRecsBatchable b = new CBIUSCollectionsDelRecsBatchable(query);
		database.executebatch(b);
		Test.stopTest();

		//verify cbi us item authorizations were deleted
		Integer i = [SELECT count() FROM Account_Auth_Feature__c where Store_CD__c = null ];
		System.assertEquals(i, 0);

	}
}