CbeerDev/objects/CBI_US_Item_Authorization_Feature__c.object
<CustomObject>
    <description>Custom Item Authorization &amp; Feature object to create and store Item Authorizations and Features that will be used by other connected sources</description>
    <fields>
        <fullName>Deletion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if a record has been inactive for 1 year and is scheduled for deletion</description>
        <label>Deletion</label>
        <type>Checkbox</type>
    </fields>
    <label>CBBD US Item Authorization &amp; Feature</label>
    <nameField>
        <displayFormat>CFA -{0000}</displayFormat>
        <label>CBBD US Item Authorization &amp; Feature</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBBD US Item Authorizations &amp; Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CbeerDev/classes/CBIUSCollectionsDelRecsSchedulable.cls
global class CBIUSCollectionsDelRecsSchedulable implements Schedulable {
	/**
	 * @description Executes the scheduled Apex job. 
	 * @param sc contains the job ID
	 */ 
	global void execute(SchedulableContext sc) {
		String query = 'SELECT Id FROM CBI_US_Item_Authorization_Feature__c where Deletion__c = true  ';
        CBIUSCollectionsDelRecsBatchable b = new CBIUSCollectionsDelRecsBatchable(query);
        database.executebatch(b);
	}
}