CbeerDev/objects/CBI_US_Item_Authorization_Feature__c.object
<CustomObject>
    <description>Custom Item Authorization &amp; Feature object to create and store Item Authorizations and Features that will be used by other connected sources</description>
    <fields>
        <fullName>Add_all_Parent_Account_stores__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When checkbox is checked, all child Accounts under Ultimate Parent Account will be automatically added as junction objects to the Item Auth/Feature</description>
        <label>Add all Parent Account stores</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BRAND_CD__c</fullName>
        <label>Brand Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FEATURE_PRICE__c</fullName>
        <label>Feature Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MASTER_PKG_CD__c</fullName>
        <label>Master Package Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MASTER_SKU_CD__c</fullName>
        <label>Master SKU Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Marketing_Groups__c</fullName>
        <label>Marketing Groups</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>NEW_SET_FLG__c</fullName>
        <label>New Set</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOTES_TXT__c</fullName>
        <label>Additional Notes</label>
        <length>290</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ON_MENU_FLG__c</fullName>
        <label>On Menu</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RESET_PERIOD_BEGIN_DT_ID__c</fullName>
        <label>Reset Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RESET_PERIOD_END_DT_ID__c</fullName>
        <label>Reset Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Report_To_Codes__c</fullName>
        <label>Report To Codes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SET_PERIOD_BEGIN_DT_ID__c</fullName>
        <label>Set Period Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SET_PERIOD_END_DT_ID__c</fullName>
        <label>Set Period End</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>States__c</fullName>
        <label>States</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sub_Accounts__c</fullName>
        <label>Sub Accounts</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TYPE_DSC__c</fullName>
        <formula>IF(AND(ISPICKVAL(Type_CD__c, &quot;BE&quot;), RecordType.DeveloperName = &quot;Feature&quot;), &quot;Beer of the Month&quot;,
   IF(AND(ISPICKVAL(Type_CD__c, &quot;HH&quot;),RecordType.DeveloperName = &quot;Feature&quot;), &quot;Happy Hour&quot;,
      IF(AND(ISPICKVAL(Type_CD__c, &quot;LP&quot;),RecordType.DeveloperName = &quot;Feature&quot;), &quot;Every Day Low Price&quot;,
         IF(AND(ISPICKVAL(Type_CD__c, &quot;LT&quot;),RecordType.DeveloperName = &quot;Feature&quot;), &quot;Limited Time Only (LTO)&quot;,
            IF(AND(ISPICKVAL(Type_CD__c, &quot;be&quot;),RecordType.DeveloperName = &quot;Feature&quot;), &quot;Beer of the Month&quot;,
               IF(AND(ISPICKVAL(Type_CD__c, &quot;hh&quot;),RecordType.DeveloperName = &quot;Feature&quot;), &quot;Happy Hour&quot;,
                  IF(AND(ISPICKVAL(Type_CD__c, &quot;lp&quot;),RecordType.DeveloperName = &quot;Feature&quot;), &quot;Every Day Low Price&quot;,
                     IF(AND(ISPICKVAL(Type_CD__c, &quot;lt&quot;),RecordType.DeveloperName = &quot;Feature&quot;), &quot;Limited Time Only (LTO)&quot;,
IF(AND(ISPICKVAL(Type_CD__c, &quot;OS&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Authorized - Optional (Sell-In)&quot;,
   IF(AND(ISPICKVAL(Type_CD__c, &quot;SP&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Authorized - Select Planogram&quot;,
      IF(AND(ISPICKVAL(Type_CD__c, &quot;BM&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Brand Mandated - Any Format&quot;,
         IF(AND(ISPICKVAL(Type_CD__c, &quot;CM&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Corporate Mandate&quot;,
            IF(AND(ISPICKVAL(Type_CD__c, &quot;NA&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Not Applicable&quot;,
               IF(AND(ISPICKVAL(Type_CD__c,&quot;PA&quot;), RecordType.DeveloperName = &quot;Item_Authorization&quot;),&quot;Pending Authorization&quot;,
                  IF(AND(ISPICKVAL(Type_CD__c, &quot;PN&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Presented - Not Authorized&quot;,
                     IF(AND(ISPICKVAL(Type_CD__c, &quot;TB&quot;), RecordType.DeveloperName = &quot;Item_Authorization&quot;),&quot;To be Presented&quot;,
                        IF(AND(ISPICKVAL(Type_CD__c, &quot;os&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Authorized - Optional (Sell-In)&quot;,
                           IF(AND(ISPICKVAL(Type_CD__c, &quot;sp&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Authorized - Select Planogram&quot;,
                             IF(AND(ISPICKVAL(Type_CD__c, &quot;bm&quot;), RecordType.DeveloperName = &quot;Item_Authorization&quot;),&quot;Brand Mandated - Any Format&quot;,
                                 IF(AND(ISPICKVAL(Type_CD__c, &quot;cm&quot;), RecordType.DeveloperName = &quot;Item_Authorization&quot;),&quot;Corporate Mandate&quot;,
                                    IF(AND(ISPICKVAL(Type_CD__c, &quot;na&quot;), RecordType.DeveloperName = &quot;Item_Authorization&quot;),&quot;Not Applicable&quot;,
                                      IF(AND(ISPICKVAL(Type_CD__c, &quot;pa&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Pending Authorization&quot;,
                                               IF(AND(ISPICKVAL(Type_CD__c, &quot;pn&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;Presented - Not Authorized&quot;,
                                                       IF(AND(ISPICKVAL(Type_CD__c, &quot;tb&quot;),RecordType.DeveloperName = &quot;Item_Authorization&quot;), &quot;To be Presented&quot;, null))))))))))))))))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Type Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type_CD__c</fullName>
        <label>Type Code</label>
        <picklist>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Ultimate_Parent__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Ultimate Parent</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>CBI_US_Collections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>CBBD US Item Authorization &amp; Feature</label>
    <nameField>
        <displayFormat>CFA -{0000}</displayFormat>
        <label>CBBD US Item Authorization &amp; Feature</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CBBD US Item Authorizations &amp; Features</pluralLabel>
    <recordTypes>
        <fullName>Feature</fullName>
        <active>true</active>
        <description>Record Type for Feature</description>
        <label>Feature</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CbeerDev/classes/CBIUSCollectionsCreateCtrl.cls
public class CBIUSCollectionsCreateCtrl extends CBIUSCollectionsCtrlBase {
	public ID rtId { get; set; }
	public CBI_US_Item_Authorization_Feature__c iaFet { get; Set; }
	public List<CBIUSCollectionsUtility.JSOption> Brands { get; set; }
	public string rt { get; set; }
	//public Account acct { get; set; }
	public Set<String> reportToCode;
	public id UltimateAccount { get; set; }
	public String currentAuthFeatureId { get; set; }
//	public CBI_US_Item_Authorization_Feature__c itemToClone { get; set; }
	public string cloneNote { get; set; }
	public string startDate { get; set; }
	public string endDate { get; set; }
	public string resetStartDate { get; set; }
	public string resetEndDate { get; set; }
	public string newSet { get; set; }
	public string onMenu { get; set; }
	public Decimal Price { get; set; }
	public String SubAccountsDisplay { get; set; }
	public String MarketingGroupsDisplay { get; set; }
	public String ReportTosDisplay { get; set; }
	public String StatesDisplay { get; set; }
	public String typeCode { get; set; }
	//public String brandCode { get; set; }
	public String skuCode { get; set; }
	public String pkgCode { get; set; }
	public String BrandNumber { get; set; }
	public String ultimateParent { get; set; }
	public String ultimateParentID { get; set; }
	public String pkgOrSkuCode { get; set; }
	public List<CBIUSCollectionsUtility.JSOption> PreloadedSkuPkgs { get; set; }
	

	//This method is used to get the recordtype f
	public string loadRecordType {
		get {
			makePageRecordType();
			return '';
		}
	}
	public CBIUSCollectionsCreateCtrl() {
		currentAuthFeatureId = ApexPages.currentPage().getParameters().get('cid');

		Brands = new LIst<CBIUSCollectionsUtility.JSOption> ();
		Brands.add(new CBIUSCollectionsUtility.JSOption('', 'Please Select'));
		Brands.addAll(CBIUSCollectionsUtility.RetrieveBrands());

		if (!String.isblank(currentAuthFeatureId)) {
			RefreshItem();

			iaFet.Id = null;
			cloneNote = iafet.NOTES_TXT__c;
			startDate = FormatDateToString(iafet.SET_PERIOD_BEGIN_DT_ID__c);
			endDate = FormatDateToString(iafet.SET_PERIOD_END_DT_ID__c);
			resetStartDate = FormatDateToString(iafet.RESET_PERIOD_BEGIN_DT_ID__c);
			resetEndDate = FormatDateToString(iafet.RESET_PERIOD_END_DT_ID__c);
			newSet = iaFet.NEW_SET_FLG__c;
			onMenu = iaFet.ON_MENU_FLG__c;
			typeCode = iaFet.Type_CD__c;
			SubAccountsDisplay = TurnPipeDelimitedToStringOrSpace(iaFet.Sub_Accounts__c);
			MarketingGroupsDisplay = TurnPipeDelimitedToStringOrSpace(iaFet.Marketing_Groups__c);
			ReportTosDisplay = TurnPipeDelimitedToStringOrSpace(iaFet.Report_To_Codes__c);
			StatesDisplay = TurnPipeDelimitedToStringOrSpace(iaFet.States__c);
			skuCode = iaFet.MASTER_SKU_CD__c;
			pkgCode = iaFet.MASTER_PKG_CD__c;
			ultimateParent = iaFet.Ultimate_Parent__r.Name;
			ultimateParentID = iaFet.Ultimate_Parent__c;
			BrandNumber = iaFet.BRand_CD__C;
			price = iaFet.FEATURE_PRICE__c;

			String pkgOrSku = 'PKG';
			pkgOrSkuCode = '';
			if (!String.isEmpty(iaFet.MASTER_PKG_CD__c)) {
				pkgOrSku = 'PKG';
				pkgOrSkuCode = iaFet.MASTER_PKG_CD__c;
			}
			if (!String.isEmpty(iaFet.MASTER_SKU_CD__c)) {
				pkgOrSku = 'SKU';
				pkgOrSkuCode = iaFet.MASTER_SKU_CD__c;
			}


			PreloadedSkuPkgs = new LIst<CBIUSCollectionsUtility.JSOption> ();
			PreloadedSkuPkgs.add(new CBIUSCollectionsUtility.JSOption('', 'Please Select'));
			PreloadedSkuPkgs.addAll(CBIUSCollectionsUtility.RetrieveSkusOrPackages(iaFet.BRAND_CD__c, pkgOrSku));

		}
	}
	public void makePageRecordType() {
		rtID = Schema.SObjectType.CBI_US_Item_Authorization_Feature__c.getRecordTypeInfosByName().get(rt).getRecordTypeId();
		iaFet = new CBI_US_Item_Authorization_Feature__c();
		iaFet.RecordTypeID = rtID;
	}
	private void RefreshItem() {
		//Query for Feature/Auth and build wrapper to support UI
		iaFet = [SELECT Id, Add_all_Parent_Account_stores__c, Type_CD__c, Ultimate_Parent__c, Ultimate_Parent__r.Name, Name, RecordType.Name, RecordType.DeveloperName, TYPE_DSC__c, BRAND_CD__c, MASTER_PKG_CD__c, MASTER_SKU_CD__c, SET_PERIOD_BEGIN_DT_ID__c, SET_PERIOD_END_DT_ID__c, RESET_PERIOD_BEGIN_DT_ID__c, RESET_PERIOD_END_DT_ID__c, Sub_Accounts__c, States__c, Report_To_Codes__c, Marketing_Groups__c, NOTES_TXT__c, ON_MENU_FLG__c, NEW_SET_FLG__c, FEATURE_PRICE__c FROM CBI_US_Item_Authorization_Feature__c WHERE Id = :currentAuthFeatureId LIMIT 1];
	}
	public String FormatDateToString(Date theDate) {
		if (theDate == null) { return ''; }
		return DateTime.newInstance(theDate.year(),
		                            theDate.month(),
		                            theDate.day()).format('MM/dd/yyyy');
	}
	public String TurnPipeDelimitedToStringOrSpace(String s) {
		if (!String.isBlank(s)) {
			List<String> values = s.split('\\|');
			return String.join(values, ', ');
		}
		return 'None';
	}
	public PageReference done() {

		PageReference p;
		try {
			insert(iaFet);
			p = Page.CBIUSItemAuthorizationEdit;
			p.setredirect(true);
			p.getParameters().put('cid', iaFet.id);
			return p;
		} catch(System.DMLException e) {
			ApexPages.addMessages(e);
			return null;
		}
		return p;
	}

	public PageReference cancelCollection() {
		return null;
	}
}